[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/kylelemons/go-gypsy"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  revision = "1fc3fd346d3cc4c610f432d8bc938bb952733873"

[[constraint]]
  name = "github.com/ziutek/mymysql"
  branch = "master"
