[[constraint]]
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  name = "github.com/kevinburke/go-gypsy"

[[constraint]]
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  name = "github.com/ziutek/mymysql"
