[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  name = "github.com/kylelemons/go-gypsy"

[[constraint]]
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  name = "github.com/ziutek/mymysql"
