on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: WillAbides/setup-go-faster@main
      with:
        go-version: 1.21.x
    - uses: actions/checkout@v4
      with:
         path: './src/github.com/kevinburke/goose'
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Run tests
      run: make race-test
      working-directory: './src/github.com/kevinburke/goose'
